{% set name = "aiolimiter" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/aiolimiter-{{ version }}.tar.gz
  sha256: 7343008c2228e89def7d4ce29ab98ee98822bf5db69018c09c90088929f7c104

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - aiolimiter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mjpieters/aiolimiter
  summary: asyncio rate limiter, a leaky bucket implementation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
